services:
  - type: web
    name: pe-prn-test-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: pe-prn-testpe
          property: connectionString
    healthCheckPath: /api/posts

databases:
  - name: pe-prn-testpe
    databaseName: pe_prn_testpe
    user: pe_prn_testpe_user
